# Overall: 

all: fullNavigation fullGuidance fullControl
	@ echo "Building full GNC program\n"
	@ # build steps
	@ echo "Full GNC program complete. See fullGNC.o in Build directory.\n"

clean:
	@ echo "Cleaning executables from Build directory\n"
	@ # rm Build/*.o
	@ echo "Executables in Build directory removed"


# Navigation: ---------------------------

fullNavigation:
	@ echo "Building all navigation programs\n"
	@ # steps
	@ echo "Navigation programs built.\n"

navigationTest:
	@ echo "Building navigation test programs\n"
	@ # steps
	@ echo "Navigation test program built to Test directory. \n"


# Guidance: -----------------------------

fullGuidance:
	@ echo "Building all guidance programs\n"
	@ # steps
	@ echo "Guidance programs built.\n"

guidanceTest:
	@ echo "Building guidance test programs\n"
	@ # steps
	@ echo "Guidance test program built to Test directory. \n"


# Control: ------------------------------

fullControl:
	@ echo "Building all control programs\n"
	@ # steps
	@ echo "Control programs built.\n"

controlTest:
	@ echo "Building control test programs\n"
	@ # steps
	@ echo "Control test program built to Test directory. \n"